baseurl = "/"
languageCode = "en-us"
title = "Posts"

theme = "hyde-y"

# Enable Disqus integration
# disqusShortname = "mhariri"


[permalinks]
    post = "/:year/:month/:day/:slug/"
    code = "/:slug/"


#
# All parameters below here are optional and can be mixed and matched.
#
[params]
    # You can use markdown here.
    brand = "![me](/media/mohsen.jpg)"
    topline = "Mohsen's corner of the Web"
    footline = ""

    # Sidebar position
    # false, true, "left", "right"
    sidebar = "left"

    # Text for the top menu link, which goes the root URL for the site.
    # Default (if omitted) is "Home".
    home = "Posts"

    # Select a syntax highight.
    # Check the static/css/highlight directory for options.
    highlight = "default"

    # Google Analytics.
    googleAnalytics = "G-4V160SVYWB"


    # Sidebar social links.
    github = "mhariri" # Your Github profile ID
    bitbucket = "" # Your Bitbucket profile ID
    linkedin = "mohsenhariri" # Your LinkedIn profile ID (from public URL)
    googleplus = "" # Your Google+ profile ID
    facebook = "" # Your Facebook profile ID
    twitter = "" # Your Twitter profile ID
    youtube = ""  # Your Youtube channel ID
    flattr = ""  # populate with your flattr uid
